import json
from datetime import datetime

def generate_markdown_report(results, target, scan_duration):
    """Génère un rapport Markdown"""
    
    # Compter les ports ouverts
    open_ports = [r for r in results if r["status"] == "open"]
    
    rapport = f"""# 🔍 PORT SCAN REPORT

**Target:** {target}  
**Scan Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Duration:** {scan_duration:.2f} seconds  
**Total Ports Scanned:** {len(results)}  
**Open Ports Found:** {len(open_ports)}

---

## 📊 SUMMARY

| Status | Count |
|--------|-------|
| Open | {len([r for r in results if r['status'] == 'open'])} |
| Closed | {len([r for r in results if r['status'] == 'closed'])} |
| Filtered | {len([r for r in results if r['status'] == 'filtered'])} |

---

## 🔓 OPEN PORTS

"""
    
    if open_ports:
        rapport += "| Port | Service | Banner | Version |\n"
        rapport += "|------|---------|--------|----------|\n"
        
        for r in open_ports:
            port = r.get("port", "?")
            service = r.get("service", "Unknown")
            banner_info = r.get("banner_info", {})
            banner_service = banner_info.get("service", "N/A")
            version = banner_info.get("version", "N/A")
            
            rapport += f"| {port} | {service} | {banner_service} | {version} |\n"
    else:
        rapport += "*No open ports found.*\n"
    
    rapport += "\n---\n\n## 📋 DETAILED RESULTS\n\n"
    
    for r in results:
        if r["status"] == "open":
            rapport += f"""
### Port {r['port']} - {r['service']} ({r['status'].upper()})

**Banner:**
```
{r.get('banner', 'No banner available')}
```

**Details:**
- Service: {r.get('banner_info', {}).get('service', 'Unknown')}
- Version: {r.get('banner_info', {}).get('version', 'Unknown')}

---
"""
    
    rapport += "\n*Report generated by Advanced Port Scanner*\n"
    
    return rapport

def generate_json_report(results, target, scan_duration):
    """Génère un rapport JSON"""
    
    report = {
        "target": target,
        "scan_date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        "duration_seconds": scan_duration,
        "total_ports": len(results),
        "open_ports": len([r for r in results if r["status"] == "open"]),
        "summary": {
            "open": len([r for r in results if r["status"] == "open"]),
            "closed": len([r for r in results if r["status"] == "closed"]),
            "filtered": len([r for r in results if r["status"] == "filtered"])
        },
        "results": results
    }
    
    return json.dumps(report, indent=2)

def generate_html_report(results, target, scan_duration):
    """Génère un rapport HTML"""
    
    open_ports = [r for r in results if r["status"] == "open"]
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Port Scan Report - {target}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: #2c3e50;
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        h1 {{ margin: 0; }}
        .info {{ margin-top: 10px; opacity: 0.9; }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }}
        .summary-card {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }}
        .summary-card h3 {{ margin-top: 0; color: #2c3e50; }}
        .summary-card .number {{ font-size: 36px; font-weight: bold; }}
        .open {{ color: #27ae60; }}
        .closed {{ color: #95a5a6; }}
        .filtered {{ color: #e74c3c; }}
        table {{
            width: 100%;
            background: white;
            border-collapse: collapse;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            border-radius: 10px;
            overflow: hidden;
        }}
        th {{
            background: #34495e;
            color: white;
            padding: 15px;
            text-align: left;
        }}
        td {{
            padding: 12px 15px;
            border-bottom: 1px solid #ecf0f1;
        }}
        tr:hover {{ background: #f8f9fa; }}
        .badge {{
            padding: 5px 10px;
            border-radius: 5px;
            font-size: 12px;
            font-weight: bold;
        }}
        .badge-open {{ background: #d4edda; color: #155724; }}
        .footer {{
            margin-top: 30px;
            text-align: center;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔍 Port Scan Report</h1>
        <div class="info">
            <strong>Target:</strong> {target}<br>
            <strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>
            <strong>Duration:</strong> {scan_duration:.2f} seconds
        </div>
    </div>
    
    <div class="summary">
        <div class="summary-card">
            <h3>Open Ports</h3>
            <div class="number open">{len([r for r in results if r['status'] == 'open'])}</div>
        </div>
        <div class="summary-card">
            <h3>Closed Ports</h3>
            <div class="number closed">{len([r for r in results if r['status'] == 'closed'])}</div>
        </div>
        <div class="summary-card">
            <h3>Filtered Ports</h3>
            <div class="number filtered">{len([r for r in results if r['status'] == 'filtered'])}</div>
        </div>
    </div>
    
    <h2>🔓 Open Ports</h2>
"""
    
    if open_ports:
        html += """
    <table>
        <thead>
            <tr>
                <th>Port</th>
                <th>Status</th>
                <th>Service</th>
                <th>Banner</th>
                <th>Version</th>
            </tr>
        </thead>
        <tbody>
"""
        for r in open_ports:
            banner_info = r.get('banner_info', {})
            html += f"""
            <tr>
                <td><strong>{r['port']}</strong></td>
                <td><span class="badge badge-open">OPEN</span></td>
                <td>{r.get('service', 'Unknown')}</td>
                <td>{banner_info.get('service', 'N/A')}</td>
                <td>{banner_info.get('version', 'N/A')}</td>
            </tr>
"""
        html += """
        </tbody>
    </table>
"""
    else:
        html += "<p>No open ports found.</p>"
    
    html += """
    <div class="footer">
        <p>Report generated by Advanced Port Scanner</p>
    </div>
</body>
</html>
"""
    
    return html

def save_report(results, target, scan_duration, format="all"):
    """
    Sauvegarde les rapports dans différents formats
    
    Args:
        results: Résultats du scan
        target: Cible scannée
        scan_duration: Durée du scan
        format: "markdown", "json", "html", ou "all"
    """
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    
    if format in ["markdown", "all"]:
        md_report = generate_markdown_report(results, target, scan_duration)
        filename = f"scan_report_{target}_{timestamp}.md"
        with open(filename, "w") as f:
            f.write(md_report)
        print(f"✅ Markdown report saved: {filename}")
    
    if format in ["json", "all"]:
        json_report = generate_json_report(results, target, scan_duration)
        filename = f"scan_report_{target}_{timestamp}.json"
        with open(filename, "w") as f:
            f.write(json_report)
        print(f"✅ JSON report saved: {filename}")
    
    if format in ["html", "all"]:
        html_report = generate_html_report(results, target, scan_duration)
        filename = f"scan_report_{target}_{timestamp}.html"
        with open(filename, "w") as f:
            f.write(html_report)
        print(f"✅ HTML report saved: {filename}")